# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoTb',
            fields=[
                ('co_id', models.AutoField(db_column='CO_ID', primary_key=True, serialize=False)),
                ('co_content', models.TextField(db_column='CO_CONTENT')),
                ('co_date', models.DateTimeField(db_column='CO_DATE')),
                ('co_registered_time', models.DateTimeField(db_column='CO_REGISTERED_TIME', default=django.utils.timezone.localtime)),
            ],
            options={
                'ordering': ['-co_date'],
            },
        ),
        migrations.CreateModel(
            name='PsTb',
            fields=[
                ('ps_id', models.AutoField(db_column='PF_ID', primary_key=True, serialize=False)),
                ('ps_title', models.CharField(db_column='PS_TITLE', max_length=100)),
                ('ps_content', models.TextField(db_column='PS_CONTENT')),
                ('ps_date', models.DateTimeField(db_column='PS_DATE')),
                ('ps_view_count', models.IntegerField(db_column='PS_VIEW_COUNT', default=0)),
                ('ps_symph', models.IntegerField(db_column='PS_SYMPH', default=0)),
                ('ps_registered_time', models.DateTimeField(db_column='PS_REGISTERED_TIME', default=django.utils.timezone.localtime)),
            ],
            options={
                'ordering': ['-ps_date'],
            },
        ),
        migrations.CreateModel(
            name='StInfoTb',
            fields=[
                ('st_id', models.AutoField(db_column='ST_ID', primary_key=True, serialize=False)),
                ('st_name', models.CharField(db_column='ST_NM', max_length=10)),
                ('st_url', models.CharField(db_column='ST_URL', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pstb',
            name='st_id',
            field=models.ForeignKey(db_column='ST_ID', on_delete=django.db.models.deletion.CASCADE, to='crawler.StInfoTb'),
        ),
        migrations.AddField(
            model_name='cotb',
            name='ps_id',
            field=models.ForeignKey(db_column='PS_ID', on_delete=django.db.models.deletion.CASCADE, to='crawler.PsTb'),
        ),
    ]
