# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoDicTb',
            fields=[
                ('codic_id', models.AutoField(db_column='CODIC_ID', primary_key=True, serialize=False)),
                ('codic_nickname', models.CharField(db_column='CODIC_NICKNAME', max_length=40)),
                ('codic_registered_time', models.DateTimeField(db_column='CODIC_REGISTERED_TIME', default=django.utils.timezone.localtime)),
            ],
        ),
        migrations.CreateModel(
            name='CoSymTb',
            fields=[
                ('cosm_id', models.AutoField(db_column='COSM_ID', primary_key=True, serialize=False)),
                ('cosm_symbol', models.CharField(db_column='COSM_SYMBOL', max_length=10)),
                ('cosm_registered_time', models.DateTimeField(db_column='COSM_REGISTERED_TIME', default=django.utils.timezone.localtime)),
            ],
        ),
        migrations.CreateModel(
            name='MtScTb',
            fields=[
                ('mtsc_id', models.AutoField(db_column='MTSC_ID', primary_key=True, serialize=False)),
                ('mtsc_score', models.IntegerField(db_column='MTSC_SCORE')),
                ('mtsc_mention', models.IntegerField(db_column='MTSC_MENTION')),
                ('mtsc_registered_time', models.DateTimeField(db_column='MTSC_REGISTERED_TIME', default=django.utils.timezone.localtime)),
                ('cosm_id', models.ForeignKey(db_column='COSM_ID', on_delete=django.db.models.deletion.CASCADE, to='analyzer.CoSymTb')),
            ],
        ),
        migrations.CreateModel(
            name='PdTb',
            fields=[
                ('pd_id', models.AutoField(db_column='PD_ID', primary_key=True, serialize=False)),
                ('pd_start', models.DateTimeField(db_column='PD_START')),
                ('pd_minutes', models.IntegerField(db_column='PD_MINUTES')),
                ('pd_registered_time', models.DateTimeField(db_column='PD_REGISTERED_TIME', default=django.utils.timezone.localtime)),
            ],
        ),
        migrations.AddField(
            model_name='mtsctb',
            name='pd_id',
            field=models.ForeignKey(db_column='PD_ID', on_delete=django.db.models.deletion.CASCADE, to='analyzer.PdTb'),
        ),
        migrations.AddField(
            model_name='codictb',
            name='cosm_id',
            field=models.ForeignKey(db_column='COSM_ID', on_delete=django.db.models.deletion.CASCADE, to='analyzer.CoSymTb'),
        ),
        migrations.AlterUniqueTogether(
            name='mtsctb',
            unique_together=set([('pd_id', 'mtsc_score')]),
        ),
    ]
