# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoDicTb',
            fields=[
                ('codic_id', models.AutoField(db_column='CODIC_ID', primary_key=True, serialize=False)),
                ('codic_nickname', models.CharField(db_column='CODIC_NICKNAME', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoNmTb',
            fields=[
                ('conm_id', models.AutoField(db_column='CONM_ID', primary_key=True, serialize=False)),
                ('conm_name', models.CharField(db_column='CONM_NAME', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MtScTb',
            fields=[
                ('mtsc_id', models.AutoField(db_column='MTSC_ID', primary_key=True, serialize=False)),
                ('mtsc_score', models.IntegerField(db_column='MTSC_SCORE')),
                ('mtsc_mention', models.IntegerField(db_column='MTSC_MENTION')),
                ('conm_id', models.ForeignKey(db_column='COMN_ID', on_delete=django.db.models.deletion.CASCADE, to='analyzer.CoNmTb')),
            ],
        ),
        migrations.CreateModel(
            name='PdTb',
            fields=[
                ('pd_id', models.AutoField(db_column='PD_ID', primary_key=True, serialize=False)),
                ('pd_start', models.DateTimeField(db_column='PD_START')),
                ('pd_minutes', models.IntegerField(db_column='PD_MINUTES')),
            ],
        ),
        migrations.AddField(
            model_name='mtsctb',
            name='pd_id',
            field=models.ForeignKey(db_column='PD_ID', on_delete=django.db.models.deletion.CASCADE, to='analyzer.PdTb'),
        ),
        migrations.AddField(
            model_name='codictb',
            name='conm_id',
            field=models.ForeignKey(db_column='CONM_ID', on_delete=django.db.models.deletion.CASCADE, to='analyzer.CoNmTb'),
        ),
        migrations.AlterUniqueTogether(
            name='mtsctb',
            unique_together=set([('pd_id', 'mtsc_score')]),
        ),
    ]
