# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conmtb',
            name='conm_name_eng',
            field=models.CharField(blank=True, db_column='CONM_NAME_ENG', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='conmtb',
            name='conm_name_ko',
            field=models.CharField(blank=True, db_column='CONM_NAME_KO', max_length=30, null=True),
        ),
    ]
