# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20180303_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conmtb',
            name='conm_name',
        ),
        migrations.AddField(
            model_name='conmtb',
            name='conm_symbol',
            field=models.CharField(db_column='CONM_SYMBOL', default='NULL', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codictb',
            name='codic_nickname',
            field=models.CharField(db_column='CODIC_NICKNAME', max_length=40),
        ),
    ]
